CC = gcc
AR = ar
C_STD= gnu99
STD = -std=$(C_STD)
name = librglMath
TARGET = ../lib/linux/$(name).a
INCS =  -I"../include/rglMath/"
CFLAGS = $(INCS) -Wall -O2 -msse -msse2 -mfpmath=sse
ARFLAGS = rcs
LIBS = -lGL -lm 
LDFLAGS = -L"." -Wl,-rpath,. $(LIBS)
OBJ  = rglVector2.o rglVector3.o rglVector4.o rglMatrix2.o rglMatrix3.o rglMatrix4.o rglMatrixGL.o 

%.o:%.c
	$(CC) $(STD) $(CFLAGS) -c $^ -o $*.o $(LIBS)

$(TARGET) : $(OBJ)
	$(AR) $(ARFLAGS)  $@ $(OBJ)
	rm  -R -f  *.o
	
clean:
	rm  -R -f  *.o
